const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8",...headers}});
const text=(data,status=200,headers={})=>new Response(data,{status,headers:{"content-type":"text/plain;charset=UTF-8",...headers}});
const now=()=>new Date().toISOString();
const b62='0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
function randomCode(n=7){let s='';for(let i=0;i<n;i++)s+=b62[Math.floor(Math.random()*b62.length)];return s}
function validUrl(v){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)}catch{return false}}
function clean(v,max=2000){return String(v??'').trim().slice(0,max)}
function cookie(name,value,maxAge=86400){return `${name}=${value}; Path=/; Max-Age=${maxAge}; HttpOnly; Secure; SameSite=Lax`}
async function hmac(secret,data){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(data));return btoa(String.fromCharCode(...new Uint8Array(sig))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
async function sessionToken(secret){const payload=btoa(JSON.stringify({exp:Date.now()+86400000})).replaceAll('=','');return payload+'.'+await hmac(secret,payload)}
async function isAuthed(request,env){const c=request.headers.get('Cookie')||'';const m=c.match(/(?:^|;\s*)sln_session=([^;]+)/);if(!m)return false;const [p,s]=m[1].split('.');if(!p||!s)return false;try{const d=JSON.parse(atob(p));if(d.exp<Date.now())return false;return (await hmac(env.SESSION_SECRET||'change-me',p))===s}catch{return false}}
function sameOrigin(request){const o=request.headers.get('Origin');return !o||o===new URL(request.url).origin}
async function requireAuth(request,env){if(!(await isAuthed(request,env)))return json({error:'未登录'},401);if(!sameOrigin(request))return json({error:'非法来源'},403);return null}
async function body(request){return await request.json().catch(()=>({}))}
function routeParts(path){return path.split('/').filter(Boolean)}
async function uniqueCode(env){for(let i=0;i<8;i++){const c=randomCode();const x=await env.DB.prepare('SELECT id FROM links WHERE code=?').bind(c).first();if(!x)return c}throw Error('无法生成唯一短码')}
async function handleApi(request,env,parts){const method=request.method,path='/'+parts.join('/');
  if(path==='/api/auth/login'&&method==='POST'){const b=await body(request);if(!env.ADMIN_PASSWORD||b.password!==env.ADMIN_PASSWORD)return json({error:'密码错误'},401);return json({ok:true},{headers:{'Set-Cookie':cookie('sln_session',await sessionToken(env.SESSION_SECRET||'change-me'))}})}
  if(path==='/api/auth/logout'&&method==='POST')return json({ok:true},{headers:{'Set-Cookie':cookie('sln_session','',0)}})
  if(path==='/api/auth/me'&&method==='GET')return json({authenticated:await isAuthed(request,env)})
  if(path==='/api/public/navigation'&&method==='GET'){const items=await env.DB.prepare('SELECT id,title,description,url,icon,category,sort_order,enabled FROM navigation WHERE enabled=1 ORDER BY sort_order,id').all();return json({items:items.results})}
  if(path==='/api/public/settings'&&method==='GET'){const r=await env.DB.prepare('SELECT key,value FROM settings').all();return json({settings:Object.fromEntries(r.results.map(x=>[x.key,x.value]))})}
  const auth=await requireAuth(request,env);if(auth)return auth;
  if(path==='/api/admin/dashboard'&&method==='GET'){const stats=await env.DB.prepare(`SELECT (SELECT COUNT(*) FROM links) links,(SELECT COALESCE(SUM(clicks),0) FROM links) clicks,(SELECT COUNT(*) FROM navigation) navigation,(SELECT COUNT(*) FROM link_visits WHERE visited_at>=datetime('now','-13 day')) recentClicks`).first();const top=await env.DB.prepare('SELECT id,code,url,title,clicks FROM links ORDER BY clicks DESC,id DESC LIMIT 8').all();const trend=await env.DB.prepare(`WITH RECURSIVE dates(d) AS (SELECT date('now','-13 day') UNION ALL SELECT date(d,'+1 day') FROM dates WHERE d<date('now')) SELECT dates.d day,COALESCE(COUNT(link_visits.id),0) clicks FROM dates LEFT JOIN link_visits ON date(link_visits.visited_at)=dates.d GROUP BY dates.d ORDER BY dates.d`).all();return json({stats,topLinks:top.results,trend:trend.results})}
  if(path==='/api/admin/links'&&method==='GET'){const r=await env.DB.prepare('SELECT * FROM links ORDER BY created_at DESC,id DESC').all();return json({items:r.results})}
  if(path==='/api/admin/links'&&method==='POST'){const b=await body(request);if(!validUrl(b.url))return json({error:'URL 必须是 http/https'},400);let code=clean(b.code,64)||await uniqueCode(env);if(!/^[A-Za-z0-9_-]{2,64}$/.test(code))return json({error:'短码格式不合法'},400);try{await env.DB.prepare('INSERT INTO links(code,url,title,description,category,enabled,updated_at) VALUES(?,?,?,?,?,?,?)').bind(code,b.url,clean(b.title,200),clean(b.description,500),clean(b.category,80),b.enabled===false?0:1,now()).run()}catch{return json({error:'短码已存在'},409)}return json({ok:true,code})}
  const lm=path.match(/^\/api\/admin\/links\/(\d+)$/);if(lm){const id=+lm[1];if(method==='PUT'){const b=await body(request);if(!validUrl(b.url))return json({error:'URL 必须是 http/https'},400);await env.DB.prepare('UPDATE links SET code=?,url=?,title=?,description=?,category=?,enabled=?,updated_at=? WHERE id=?').bind(clean(b.code,64),b.url,clean(b.title,200),clean(b.description,500),clean(b.category,80),b.enabled===false?0:1,now(),id).run();return json({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM links WHERE id=?').bind(id).run();return json({ok:true})}}
  if(path==='/api/admin/navigation'&&method==='GET'){const r=await env.DB.prepare('SELECT * FROM navigation ORDER BY sort_order,id').all();return json({items:r.results})}
  if(path==='/api/admin/navigation'&&method==='POST'){const b=await body(request);if(!validUrl(b.url)||!clean(b.title,120))return json({error:'标题和 URL 必填'},400);const mx=await env.DB.prepare('SELECT COALESCE(MAX(sort_order),-1) m FROM navigation').first();await env.DB.prepare('INSERT INTO navigation(title,description,url,icon,category,sort_order,enabled,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(clean(b.title,120),clean(b.description,500),b.url,clean(b.icon,500),clean(b.category,80),(mx.m??-1)+1,b.enabled===false?0:1,now()).run();return json({ok:true})}
  if(path==='/api/admin/navigation/reorder'&&method==='POST'){const b=await body(request);if(!Array.isArray(b.ids))return json({error:'排序数据无效'},400);const stmts=b.ids.map((id,i)=>env.DB.prepare('UPDATE navigation SET sort_order=?,updated_at=? WHERE id=?').bind(i,now(),id));await env.DB.batch(stmts);return json({ok:true})}
  const nm=path.match(/^\/api\/admin\/navigation\/(\d+)$/);if(nm){const id=+nm[1];if(method==='PUT'){const b=await body(request);if(!validUrl(b.url))return json({error:'URL 无效'},400);await env.DB.prepare('UPDATE navigation SET title=?,description=?,url=?,icon=?,category=?,enabled=?,updated_at=? WHERE id=?').bind(clean(b.title,120),clean(b.description,500),b.url,clean(b.icon,500),clean(b.category,80),b.enabled===false?0:1,now(),id).run();return json({ok:true})}if(method==='DELETE'){await env.DB.prepare('DELETE FROM navigation WHERE id=?').bind(id).run();return json({ok:true})}}
  if(path==='/api/admin/settings'&&method==='GET'){const r=await env.DB.prepare('SELECT key,value FROM settings').all();return json({settings:Object.fromEntries(r.results.map(x=>[x.key,x.value]))})}
  if(path==='/api/admin/settings'&&method==='PUT'){const b=await body(request);const allowed=['site_title','site_subtitle','site_description','accent'];const stmts=allowed.filter(k=>k in b).map(k=>env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(k,clean(b[k],500)));if(stmts.length)await env.DB.batch(stmts);return json({ok:true})}
  return json({error:'Not found'},404)
}
export default {async fetch(request,env,ctx){const url=new URL(request.url),parts=routeParts(url.pathname);try{if(parts[0]==='api')return await handleApi(request,env,parts);if(parts.length===1&&parts[0]&&parts[0]!=='admin'){const code=parts[0];const l=await env.DB.prepare('SELECT * FROM links WHERE code=? AND enabled=1').bind(code).first();if(l){ctx.waitUntil(Promise.all([env.DB.prepare('UPDATE links SET clicks=clicks+1,last_clicked_at=?,updated_at=? WHERE id=?').bind(now(),now(),l.id).run(),env.DB.prepare('INSERT INTO link_visits(link_id,visited_at) VALUES(?,?)').bind(l.id,now()).run()]));return Response.redirect(l.url,302)}}return env.ASSETS.fetch(request)}catch(e){return json({error:e.message||'Server error'},500)}}}